name: proj
description: Instant Communication, Delivered Express
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  bloc: ^8.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  http: ^1.1.0
  logging: ^1.2.0
  meta: ^1.9.1
  web_socket_channel: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/Background.png
    - assets/images/Avatar.jpg
    - assets/images/Logo.png
    # Icons
    - assets/icons/Sign_out_circle.png
    - assets/icons/Table.png
    - assets/icons/Chat.png
    - assets/icons/Edit.png
  fonts:
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC-Regular.ttf
        - asset: assets/fonts/NotoSansTC-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansTC-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansTC-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansTC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansTC-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansTC-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansTC-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansTC-Black.ttf
          weight: 900
